<a href="https://colab.research.google.com/github/riyastanley/Exploratory-Data-Analysis-/blob/main/exp2_eda_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns

In [ ]:
df = pd.read_csv("/1000 Sales Records.csv")

In [ ]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45

In [ ]:
df.head(7)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
5,Europe,Armenia,Cereal,Online,H,11/24/2014,683458888,12/28/2014,9528,205.70,117.11,1959909.60,1115824.08,844085.52
6,Sub-Saharan Africa,Eritrea,Cereal,Online,H,3/4/2015,679414975,4/17/2015,2844,205.70,117.11,585010.80,333060.84,251949.96

In [ ]:
df.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
5,Europe,Armenia,Cereal,Online,H,11/24/2014,683458888,12/28/2014,9528,205.70,117.11,1959909.60,1115824.08,844085.52
6,Sub-Saharan Africa,Eritrea,Cereal,Online,H,3/4/2015,679414975,4/17/2015,2844,205.70,117.11,585010.80,333060.84,251949.96
7,Europe,Montenegro,Clothes,Offline,M,5/17/2012,208630645,6/28/2012,7299,109.28,35.84,797634.72,261596.16,536038.56
8,Central America and the Caribbean,Jamaica,Vegetables,Online,H,1/29/2015,266467225,3/7/2015,2428,154.06,90.93,374057.68,220778.04,153279.64
9,Australia and Oceania,Fiji,Vegetables,Offline,H,12/24/2013,118598544,1/19/2014,4800,154.06,90.93,739488.00,436464.00,303024.00

In [ ]:
df['Country'].dtype

dtype('O')

In [ ]:
df['Unit Price'].dtype

dtype('float64')

In [ ]:
df.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [ ]:
total_records = len(df)
print(total_records)

1000

In [ ]:
print(df.columns)

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [ ]:
df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+03,1000.000000,1000.00000,1000.000000,1.000000e+03,1.000000e+03,1.000000e+03
mean,5.496813e+08,5053.988000,262.10684,184.965110,1.327322e+06,9.361192e+05,3.912026e+05
std,2.571334e+08,2901.375317,216.02106,175.289311,1.486515e+06,1.162571e+06,3.836402e+05
min,1.029280e+08,13.000000,9.33000,6.920000,2.043250e+03,1.416750e+03,5.326100e+02
25%,3.280740e+08,2420.250000,81.73000,56.670000,2.811919e+05,1.649319e+05,9.837612e+04
50%,5.566097e+08,5184.000000,154.06000,97.440000,7.549392e+05,4.647261e+05,2.772260e+05
75%,7.696945e+08,7536.750000,421.89000,263.330000,1.733503e+06,1.141750e+06,5.484568e+05
max,9.955298e+08,9998.000000,668.27000,524.960000,6.617210e+06,5.204978e+06,1.726181e+06

In [ ]:
df.max()

Region            Sub-Saharan Africa
Country                     Zimbabwe
Item Type                 Vegetables
Sales Channel                 Online
Order Priority                     M
Order Date                  9/8/2015
Order ID                   995529830
Ship Date                   9/9/2016
Units Sold                      9998
Unit Price                    668.27
Unit Cost                     524.96
Total Revenue             6617209.54
Total Cost                 5204978.4
Total Profit              1726181.36
dtype: object

In [ ]:
df.mean(numeric_only=True)

Order ID         5.496813e+08
Units Sold       5.053988e+03
Unit Price       2.621068e+02
Unit Cost        1.849651e+02
Total Revenue    1.327322e+06
Total Cost       9.361192e+05
Total Profit     3.912026e+05
dtype: float64

In [ ]:
df.min(numeric_only=True)

Order ID         1.029280e+08
Units Sold       1.300000e+01
Unit Price       9.330000e+00
Unit Cost        6.920000e+00
Total Revenue    2.043250e+03
Total Cost       1.416750e+03
Total Profit     5.326100e+02
dtype: float64

In [ ]:
df.max(numeric_only=True)

Order ID         9.955298e+08
Units Sold       9.998000e+03
Unit Price       6.682700e+02
Unit Cost        5.249600e+02
Total Revenue    6.617210e+06
Total Cost       5.204978e+06
Total Profit     1.726181e+06
dtype: float64

In [ ]:
df.median(numeric_only=True)

Order ID         5.566097e+08
Units Sold       5.184000e+03
Unit Price       1.540600e+02
Unit Cost        9.744000e+01
Total Revenue    7.549392e+05
Total Cost       4.647261e+05
Total Profit     2.772260e+05
dtype: float64

In [ ]:
df.std(numeric_only=True)

Order ID         2.571334e+08
Units Sold       2.901375e+03
Unit Price       2.160211e+02
Unit Cost        1.752893e+02
Total Revenue    1.486515e+06
Total Cost       1.162571e+06
Total Profit     3.836402e+05
dtype: float64

In [ ]:
df.sample()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
901,Asia,Japan,Cosmetics,Online,L,1/6/2016,453569972,2/19/2016,289,437.2,263.33,126350.8,76102.37,50248.43

In [ ]:
df.dropna()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Middle East and North Africa,Azerbaijan,Snacks,Offline,C,4/18/2010,534085166,4/25/2010,6524,152.58,97.44,995431.92,635698.56,359733.36
996,Europe,Georgia,Baby Food,Offline,H,8/1/2011,590768182,9/7/2011,288,255.28,159.42,73520.64,45912.96,27607.68
997,Middle East and North Africa,United Arab Emirates,Vegetables,Online,C,5/12/2011,524363124,6/28/2011,9556,154.06,90.93,1472197.36,868927.08,603270.28
998,Europe,Finland,Household,Offline,L,1/25/2016,289606320,2/14/2016,9801,668.27,502.54,6549714.27,4925394.54,1624319.73
999,Europe,Portugal,Cereal,Offline,C,4/10/2014,811546599,5/8/2014,3528,205.70,117.11,725709.60,413164.08,312545.52

In [ ]:
first_50 = df.head(50)
print(first_50.mean(numeric_only=True))

Order ID         4.844509e+08
Units Sold       5.037020e+03
Unit Price       2.611640e+02
Unit Cost        1.881152e+02
Total Revenue    1.322732e+06
Total Cost       9.690889e+05
Total Profit     3.536435e+05
dtype: float64

In [ ]:
print(df['Units Sold'].mean())

5053.988

In [ ]:
country=df.groupby(['Country'])

In [ ]:
country.mean(numeric_only=True)

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
Country,,,,,,,
Afghanistan,6.586300e+08,3775.166667,149.095000,78.706667,4.739315e+05,2.463637e+05,227567.850000
Albania,6.899045e+08,5678.875000,204.493750,137.526250,1.213737e+06,8.208539e+05,392883.542500
Algeria,2.168614e+08,6955.800000,312.834000,239.334000,2.054518e+06,1.607320e+06,447197.848000
Andorra,5.826290e+08,4592.571429,269.137143,195.065714,1.021875e+06,7.156934e+05,306181.267143
Angola,3.838087e+08,5118.125000,335.386250,242.013750,1.955379e+06,1.387736e+06,567643.052500
...,...,...,...,...,...,...,...
Vatican City,5.518604e+08,4104.750000,115.842500,64.000000,3.938448e+05,2.312742e+05,162570.662500
Vietnam,5.138378e+08,4869.142857,340.467143,245.387143,1.666862e+06,1.171694e+06,495167.371429
Yemen,5.527234e+08,5316.500000,401.050000,284.481667,1.968911e+06,1.355968e+06,612942.638333
Zambia,5.958717e+08,5525.000000,132.305000,83.170000,9.770581e+05,6.120905e+05,364967.600000
Zimbabwe,5.543018e+08,5078.900000,156.435000,117.988000,6.928978e+05,5.385405e+05,154357.291000

In [ ]:
df_sub = df[ df['Units Sold'] > 9000]
print(df_sub)

                                Region                   Country  \
4                   Sub-Saharan Africa                      Chad
5                               Europe                   Armenia
22        Middle East and North Africa                   Algeria
25   Central America and the Caribbean                   Grenada
28                  Sub-Saharan Africa                      Chad
..                                 ...                       ...
974       Middle East and North Africa                    Jordan
975  Central America and the Caribbean                    Panama
976                 Sub-Saharan Africa  Central African Republic
997       Middle East and North Africa      United Arab Emirates
998                             Europe                   Finland

         Item Type Sales Channel Order Priority  Order Date   Order ID  \
4           Fruits       Offline              H   8/16/2011  645713555
5           Cereal        Online              H  11/24/2014  683458888
22   Personal Care        Online              H   2/20/2011  127468717
25       Beverages        Online              M   1/30/2017  397877871
28            Meat       Offline              H   1/20/2016  357222878
..             ...           ...            ...         ...        ...
974        Clothes        Online              M   8/12/2011  812984693
975           Meat       Offline              C  12/18/2012  775171554
976      Household        Online              H   1/10/2010  256994950
997     Vegetables        Online              C   5/12/2011  524363124
998      Household       Offline              L   1/25/2016  289606320

      Ship Date  Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
4     8/31/2011        9845        9.33       6.92       91853.85    68127.40
5    12/28/2014        9528      205.70     117.11     1959909.60  1115824.08
22     3/9/2011        9681       81.73      56.67      791228.13   548622.27
25    3/20/2017        9759       47.45      31.79      463064.55   310238.61
28     3/9/2016        9043      421.89     364.69     3815151.27  3297891.67
..          ...         ...         ...        ...            ...         ...
974   8/22/2011        9092      109.28      35.84      993573.76   325857.28
975    1/5/2013        9344      421.89     364.69     3942140.16  3407663.36
976   2/19/2010        9372      668.27     502.54     6263026.44  4709804.88
997   6/28/2011        9556      154.06      90.93     1472197.36   868927.08
998   2/14/2016        9801      668.27     502.54     6549714.27  4925394.54

     Total Profit
4        23726.45
5       844085.52
22      242605.86
25      152825.94
28      517259.60
..            ...
974     667716.48
975     534476.80
976    1553221.56
997     603270.28
998    1624319.73

[93 rows x 14 columns]

In [ ]:
print(df.loc[10:20,['Item Type','Ship Date','Unit Price']])

          Item Type   Ship Date  Unit Price
10          Clothes   1/19/2016      109.28
11           Snacks   3/18/2010      152.58
12        Household  12/22/2016      668.27
13        Cosmetics    1/5/2016      437.20
14           Fruits    2/6/2011        9.33
15          Clothes   7/22/2010      109.28
16  Office Supplies   5/12/2016      651.21
17        Beverages    8/7/2012       47.45
18          Clothes   10/3/2014      109.28
19        Household    9/8/2012      668.27
20           Snacks  10/15/2012      152.58

In [ ]:
print(df_sub.iloc[10:20,[0, 1, 2, 5]])

                                Region                   Country  \
72                  Sub-Saharan Africa                Cape Verde
79                       North America  United States of America
91   Central America and the Caribbean               El Salvador
110              Australia and Oceania                     Tonga
133                             Europe                   Germany
137                               Asia                Uzbekistan
146                             Europe                    Serbia
171                             Europe                Luxembourg
172                 Sub-Saharan Africa                 Swaziland
195       Middle East and North Africa                   Lebanon

           Item Type  Order Date
72         Beverages  10/23/2013
79   Office Supplies    6/9/2017
91           Clothes    8/7/2010
110        Beverages   1/27/2010
133        Baby Food  11/13/2015
137    Personal Care   2/12/2013
146           Snacks   9/20/2013
171        Household   8/15/2014
172    Personal Care    7/6/2017
195        Household    3/8/2016

In [ ]:
print(df.iloc[0])

Region            Middle East and North Africa
Country                                  Libya
Item Type                            Cosmetics
Sales Channel                          Offline
Order Priority                               M
Order Date                          10/18/2014
Order ID                             686800706
Ship Date                           10/31/2014
Units Sold                                8446
Unit Price                               437.2
Unit Cost                               263.33
Total Revenue                        3692591.2
Total Cost                          2224085.18
Total Profit                        1468506.02
Name: 0, dtype: object

In [ ]:
print(df.iloc[:, 0])

0      Middle East and North Africa
1                     North America
2      Middle East and North Africa
3                              Asia
4                Sub-Saharan Africa
                   ...
995    Middle East and North Africa
996                          Europe
997    Middle East and North Africa
998                          Europe
999                          Europe
Name: Region, Length: 1000, dtype: object

In [ ]:
print(df.iloc[0:5])

                         Region Country   Item Type Sales Channel  \
0  Middle East and North Africa   Libya   Cosmetics       Offline
1                 North America  Canada  Vegetables        Online
2  Middle East and North Africa   Libya   Baby Food       Offline
3                          Asia   Japan      Cereal       Offline
4            Sub-Saharan Africa    Chad      Fruits       Offline

  Order Priority  Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
0              M  10/18/2014  686800706  10/31/2014        8446      437.20
1              M   11/7/2011  185941302   12/8/2011        3018      154.06
2              C  10/31/2016  246222341   12/9/2016        1517      255.28
3              C   4/10/2010  161442649   5/12/2010        3322      205.70
4              H   8/16/2011  645713555   8/31/2011        9845        9.33

   Unit Cost  Total Revenue  Total Cost  Total Profit
0     263.33     3692591.20  2224085.18    1468506.02
1      90.93      464953.08   274426.74     190526.34
2     159.42      387259.76   241840.14     145419.62
3     117.11      683335.40   389039.42     294295.98
4       6.92       91853.85    68127.40      23726.45

In [ ]:
print(df.iloc[0:4, 0:4])

                         Region Country   Item Type Sales Channel
0  Middle East and North Africa   Libya   Cosmetics       Offline
1                 North America  Canada  Vegetables        Online
2  Middle East and North Africa   Libya   Baby Food       Offline
3                          Asia   Japan      Cereal       Offline