<a href="https://colab.research.google.com/github/riyastanley/Exploratory-Data-Analysis-/blob/main/exp3_eda_28_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [ ]:
dfx['store4'] = np.nan

In [ ]:
dfx.loc['watermelon'] = np.arange(15, 19)

In [ ]:
dfx.loc['oranges'] = np.nan

In [ ]:
dfx['store5'] = np.nan

In [ ]:
dfx.loc['apple','store4'] = 20

In [ ]:
dfx

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [ ]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [ ]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [ ]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [ ]:
total=dfx.isnull().sum().sum()
print(total)

15

In [ ]:
print(dfx.count())

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

In [ ]:
dfx.store4[dfx.store4.notnull()]

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

In [ ]:
dfx.store4.dropna()

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [ ]:
ar1 = np.array([100, 200, np.nan, 300])mean1=

In [ ]:
ser1 = pd.Series(ar1)

In [ ]:
ar1.mean()

np.float64(nan)

In [ ]:
ser1.mean()

np.float64(200.0)

In [ ]:
ser2 = dfx.store4

In [ ]:
ser2.sum()

np.float64(38.0)

In [ ]:
ser2.mean()

np.float64(19.0)

In [ ]:
ser2.cumsum()

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

In [32]:
filledDf = dfx.fillna(0)
filledDf

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [33]:
dfx.mean()
filledDf.mean()

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

In [34]:
dfx.store4.fillna(method='ffill')
dfx.store4.fillna(method='bfill')

/tmp/ipykernel_3117/3468375107.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')
/tmp/ipykernel_3117/3468375107.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')

apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

In [35]:
#imputation_techniques

In [37]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [38]:
df = pd.DataFrame(
{
"Age": [25, np.nan, 30, 45, 22],
"Salary": [50000, 60000, np.nan, 80000, 45000],
"Category": ["A", "B", "A", np.nan, "B"],
}
)

In [39]:
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])

In [40]:
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])

In [43]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()

In [44]:
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
print(df)

    Age   Salary Category  Age_Mean  Salary_Median Category_Mode   Age_MICE  \
0  25.0  50000.0        A      25.0        50000.0             A  25.000000
1   NaN  60000.0        B      30.5        60000.0             B  31.766487
2  30.0      NaN        A      30.0        55000.0             A  30.000000
3  45.0  80000.0      NaN      45.0        80000.0             A  45.000000
4  22.0  45000.0        B      22.0        45000.0             B  22.000000

    Salary_MICE
0  50000.000000
1  60000.000000
2  57324.583367
3  80000.000000
4  45000.000000